### PR TITLE
Change api add output profile

### PR DESCRIPTION
**Pull request by okdshin**
This PR contains
- `array_profile` which has `dtype` and `dims`
- deprecated `menoh_variable_table_builder_add_output_profile`
- new api: `menoh_variable_table_builder_add_output_name`
- `context` taking `std::unordered_map<std::string, array_profile> output_profile_table`

### CODE REVIEW

**Comment by msakai** [comment]
I guess you also want to update C++ API.

**Comment by msakai** [comment]
Just a confirmation:
`menoh/model.hpp`, `menoh/model.cpp`, `test/model.cpp`, `test/mkldnn.cpp` are deleted.
Was `menoh::impl` no longer in use?
And are tests in `test/mkldnn.cpp` no longer necessary?

**Comment by okdshin** [comment]
I updated C++ API.

**Comment by okdshin** [comment]
`menoh/model.hpp`, `menoh/model.cpp` are legacy codes that no API depends on them. Only `test/model.cpp` depends on the `model.hpp` but useless for users. So we can delete them.
 `test/mkldnn.cpp` is the problem. I plan to replace `test/mkldnn.cpp` with more general test suite. However it does not exist yet. I will return it.

**Comment by okdshin** [comment]
Sorry I misunderstood. `test/mkldnn.cpp` is also useless.

**Comment by msakai** [comment]
Thanks for the clarification!

**Comment by okdshin** [comment]
`menoh::impl` disappears with merging this PR but blackbox tests will be added and they needs it.

**Pull request merged**
