### PR TITLE
WIP: Rename libonnx libmenoh onnx

### PR DESCRIPTION
**Pull request by okdshin**
This PR makes libmenoh_onnx.a and libmenoh_onnx_proto.a for building menoh as static library

### CODE REVIEW

**Comment by okdshin** [comment]
Sorry. There is a bug. I'll fix.

**Comment by msakai** [comment]
The same problem happens in my environment and it happens even if I cleaned build directory.

I guess that we need to do `set(ONNX_NAMESPACE "menoh_onnx" CACHE INTERNAL "onnx namespace")` instead of `set(ONNX_NAMESPACE "menoh_onnx")`.
Otherwise, `set(ONNX_NAMESPACE "onnx" CACHE STRING "onnx namespace")` in `external/onnx/CMakeLists.txt` overrides its value?

**Comment by okdshin** [comment]
I see. I will do so.

**Comment by msakai** [comment]
AppVeyor/TravisCI builds succeeded.
Is there any remaining issue?

**Comment by okdshin** [comment]
Thanks for reviwing. Sorry for my late reply.

**Pull request merged**
